services:
  test-backend-dotnet-queue2-core-tests:
    build:
      target: development
    image: test-backend-dotnet-queue2-core-tests-development
    container_name: test-backend-dotnet-queue2-core-tests
    user: root
    entrypoint: sh -c "cd /home/dotnet && chown -R dotnet:dotnet . && su dotnet -c 'dotnet watch --project test/Test.Backend.Dotnet.Queue2.Core.Tests/Test.Backend.Dotnet.Queue2.Core.Tests.csproj test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./test-output/'"
    volumes:
      - ./src/Test.Backend.Dotnet.Queue2.Core:/home/dotnet/src/Test.Backend.Dotnet.Queue2.Core
      - ./test/Test.Backend.Dotnet.Queue2.Core.Tests:/home/dotnet/test/Test.Backend.Dotnet.Queue2.Core.Tests
      - ./test-output:/home/dotnet/Test.Backend.Dotnet.Queue2.Core.Tests/test-output

  test-backend-dotnet-queue2-api-tests:
    build:
      target: development
    image: test-backend-dotnet-queue2-api-tests-development
    container_name: test-backend-dotnet-queue2-api-tests
    user: root
    entrypoint: sh -c "cd /home/dotnet && chown -R dotnet:dotnet . && su dotnet -c 'dotnet watch --project test/Test.Backend.Dotnet.Queue2.Api.Tests/Test.Backend.Dotnet.Queue2.Api.Tests.csproj test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./test-output/'"
    volumes:
      - ./src/Test.Backend.Dotnet.Queue2.Api:/home/dotnet/src/Test.Backend.Dotnet.Queue2.Api
      - ./test/Test.Backend.Dotnet.Queue2.Api.Tests:/home/dotnet/test/Test.Backend.Dotnet.Queue2.Api.Tests
      - ./test-output:/home/dotnet/Test.Backend.Dotnet.Queue2.Api.Tests/test-output